### PR TITLE
Update user guide/developer guide for Activity command

### PR DESCRIPTION
**Pull request by daekoon**
### Context
Behaviour of Activity command was slightly changed during the development. It now uses keyword-based searching instead of doing a complete match with full name, which improves usability. Furthermore, keywords with wrong matches are ignored with a warning message, instead of creating a new Contact object.

### Changes
- Update user guide for Activity command
- Create section on "Activity class" for Developer Guide
- Create section on "Create Activity feature" for Developer Guide

### CODE REVIEW

**Comment by podocarp** [comment]
Hey coverage decreased, I suggest you add tests for your new documentation

**Comment by podocarp** [comment]
Ooo coverage is great now, seems like you added tests to your documentation.

**Comment by Aulud** [comment]
> Ooo coverage is great now, seems like you added tests to your documentation.

How is this even a thing?

**Review by JohnNzj — APPROVED** [review]
LGTM

**Pull request merged**
